# Generated by Django 4.2.1 on 2023-07-02 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chetdan_buyurtma',
            name='maxsulot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materio.maxsulot'),
        ),
    ]
