# Generated by Django 4.2.1 on 2023-07-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materio', '0002_chetdan_buyurtma_maxsulot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maxsulot',
            name='entry_price_type',
            field=models.CharField(choices=[('USD', 'USD'), ('YUAN', 'YUAN'), ('UZS', 'UZS')], max_length=128),
        ),
        migrations.AlterField(
            model_name='maxsulot',
            name='product_price_type',
            field=models.CharField(choices=[('USD', 'USD'), ('YUAN', 'YUAN'), ('UZS', 'UZS')], max_length=128),
        ),
    ]
