# Generated by Django 4.2.1 on 2023-07-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materio', '0003_alter_maxsulot_entry_price_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='price_type',
            field=models.CharField(choices=[('USD', 'USD'), ('YUAN', 'YUAN'), ('UZS', 'UZS')], max_length=128),
        ),
    ]
