# Generated by Django 4.2.3 on 2023-07-10 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materio', '0004_alter_basket_price_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savdo_oynasi',
            name='maxsulot_nomi',
        ),
        migrations.RemoveField(
            model_name='savdo_oynasi',
            name='maxsulot_rangi',
        ),
        migrations.RemoveField(
            model_name='savdo_oynasi',
            name='size',
        ),
        migrations.RemoveField(
            model_name='savdo_oynasi',
            name='soni',
        ),
        migrations.AddField(
            model_name='savdo_oynasi',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materio.maxsulot'),
        ),
    ]
