# Generated by Django 4.2.3 on 2023-07-10 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materio', '0005_remove_savdo_oynasi_maxsulot_nomi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savdo_oynasi',
            name='clent_bolsa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
